#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
拉曼光谱边缘客户端 - 命令行接口

提供命令行模式支持，允许外部程序调用光谱采集和分析功能

使用方法:
    # 采集光谱并保存
    python cli.py --acquire --output result.csv
    
    # 谱库匹配
    python cli.py --match sample.csv --top-3
    
    # 显示帮助
    python cli.py --help
"""
import sys
import os
import argparse
import json
import time
from pathlib import Path
from typing import Optional, List

# 添加项目根目录到路径
sys.path.insert(0, str(Path(__file__).parent))

import numpy as np

from backend.driver import MockDriver
from backend.inference import MockInference
from backend.logging_config import setup_logging, cleanup_old_logs, get_logger

# 初始化日志
cleanup_old_logs()
setup_logging(console_output=True, log_file=None)
logger = get_logger(__name__)


def acquire_spectrum(
    output_path: str,
    integration_time: int = 100,
    accumulation_count: int = 1,
    smoothing_window: int = 0,
    noise_level: float = 0.02,
    format: str = 'csv'
) -> bool:
    """
    采集光谱并保存
    
    Args:
        output_path: 输出文件路径
        integration_time: 积分时间 (ms)
        accumulation_count: 累加次数
        smoothing_window: 平滑窗口
        noise_level: 噪声水平
        format: 输出格式 (csv/json)
    
    Returns:
        是否成功
    """
    logger.info(f"[CLI] 开始采集光谱...")
    
    # 初始化驱动
    driver = MockDriver(seed=42, noise_level=noise_level)
    driver.connect()
    
    if not driver.connected:
        logger.error("[CLI] 设备连接失败")
        return False
    
    # 设置参数
    driver.set_params(
        integration_time=integration_time,
        accumulation_count=accumulation_count
    )
    
    # 采集光谱
    spectrum = driver.read_spectrum()
    wavelengths = driver.get_wavelengths()
    
    if spectrum is None:
        logger.error("[CLI] 光谱读取失败")
        driver.disconnect()
        return False
    
    # 平滑处理
    if smoothing_window > 1:
        inference = MockInference()
        spectrum = inference.smooth(spectrum, smoothing_window)
    
    driver.disconnect()
    
    # 保存数据
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    if format.lower() == 'json':
        if not output_file.suffix:
            output_file = output_file.with_suffix('.json')
        data = {
            "disclaimer": "⚠️ 重要提示：本数据由模拟驱动生成，仅用于教学演示，不可用于实际物质分析。",
            "metadata": {
                "integration_time": integration_time,
                "accumulation_count": accumulation_count,
                "smoothing_window": smoothing_window,
                "noise_level": noise_level,
                "wavelength_range": [float(wavelengths.min()), float(wavelengths.max())],
                "num_points": len(wavelengths)
            },
            "wavelengths": wavelengths.tolist(),
            "spectrum": spectrum.tolist()
        }
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    
    elif format.lower() == 'csv':
        if not output_file.suffix:
            output_file = output_file.with_suffix('.csv')
        with open(output_file, 'w', newline='', encoding='utf-8') as f:
            f.write("# ⚠️ 免责声明：本数据由模拟驱动生成，仅用于教学演示，不可用于实际物质分析。\n")
            f.write("# Disclaimer: This data is generated by mock driver, for teaching/demo purposes only.\n\n")
            f.write("Wavenumber (cm^-1),Intensity (a.u.)\n")
            for i, wl in enumerate(wavelengths):
                f.write(f"{wl},{spectrum[i]}\n")
    
    logger.info(f"[CLI] 光谱已保存到：{output_file}")
    return True


def match_library(
    input_path: str,
    top_k: int = 5,
    threshold: float = 0.6
) -> bool:
    """
    谱库匹配
    
    Args:
        input_path: 输入光谱文件路径 (CSV/JSON)
        top_k: 返回最匹配的 k 个结果
        threshold: 匹配阈值
    
    Returns:
        是否成功
    """
    logger.info(f"[CLI] 执行谱库匹配：{input_path}")
    
    # 读取光谱数据
    input_file = Path(input_path)
    if not input_file.exists():
        logger.error(f"[CLI] 文件不存在：{input_path}")
        return False
    
    inference = MockInference()
    
    # 加载光谱
    if input_file.suffix.lower() == '.json':
        with open(input_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        wavelengths = np.array(data.get('wavelengths', []))
        spectrum = np.array(data.get('spectrum', []))
    elif input_file.suffix.lower() == '.csv':
        # 跳过免责声明行和标题行
        data = np.loadtxt(input_file, delimiter=',', comments='#', skiprows=4, encoding='utf-8')
        wavelengths = data[:, 0]
        spectrum = data[:, 1]
    else:
        logger.error(f"[CLI] 不支持的文件格式：{input_file.suffix}")
        return False
    
    # 谱库匹配
    results = inference.match_library(spectrum, wavelengths, top_k=top_k)
    
    if not results:
        logger.warning("[CLI] 未找到匹配结果")
        return False
    
    # 输出结果
    print("\n" + "=" * 60)
    print("📚 谱库匹配结果")
    print("=" * 60)
    
    for i, result in enumerate(results):
        score = result.get('score', 0)
        name = result.get('name', 'unknown')
        is_match = result.get('is_match', False)
        
        marker = "✓" if is_match else "✗"
        print(f"\n#{i+1} {marker} {name}")
        print(f"   匹配度：{score*100:.1f}%")
        
        if is_match and score >= threshold:
            print(f"   → 找到匹配物质！")
    
    print("\n" + "=" * 60)
    print("⚠️ 免责声明：本谱库为模拟谱库，仅用于教学演示，不可用于实际物质分析。")
    print("=" * 60 + "\n")
    
    # 保存结果
    output_file = input_file.with_suffix('.match.json')
    match_data = {
        "disclaimer": "⚠️ 重要提示：本谱库为模拟谱库，仅用于教学演示，不可用于实际物质分析。",
        "input_file": str(input_file),
        "matches": [
            {
                "name": r.get('name', 'unknown'),
                "score": float(r.get('score', 0)),
                "is_match": bool(r.get('is_match', False))
            }
            for r in results
        ]
    }
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(match_data, f, indent=2, ensure_ascii=False)
    
    logger.info(f"[CLI] 匹配结果已保存到：{output_file}")
    return True


def analyze_spectrum(
    input_path: str,
    output_path: Optional[str] = None
) -> bool:
    """
    分析光谱（峰值检测、峰面积计算等）
    
    Args:
        input_path: 输入光谱文件路径
        output_path: 输出结果路径（可选）
    
    Returns:
        是否成功
    """
    logger.info(f"[CLI] 分析光谱：{input_path}")
    
    # 读取光谱数据
    input_file = Path(input_path)
    if not input_file.exists():
        logger.error(f"[CLI] 文件不存在：{input_path}")
        return False
    
    inference = MockInference()
    
    # 加载光谱
    if input_file.suffix.lower() == '.json':
        with open(input_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        wavelengths = np.array(data.get('wavelengths', []))
        spectrum = np.array(data.get('spectrum', []))
    elif input_file.suffix.lower() == '.csv':
        # 跳过免责声明行和标题行
        data = np.loadtxt(input_file, delimiter=',', comments='#', skiprows=4, encoding='utf-8')
        wavelengths = data[:, 0]
        spectrum = data[:, 1]
    else:
        logger.error(f"[CLI] 不支持的文件格式：{input_file.suffix}")
        return False
    
    # 峰值检测
    peaks = inference._detect_peaks(spectrum, wavelengths)
    
    # 输出结果
    print("\n" + "=" * 60)
    print("📊 光谱分析结果")
    print("=" * 60)
    
    print(f"\n📈 检测到 {len(peaks)} 个特征峰:\n")
    print(f"{'序号':<6} {'位置 (cm⁻¹)':<15} {'强度':<15} {'半高宽':<15}")
    print("-" * 60)
    
    for i, peak in enumerate(peaks):
        print(f"{i+1:<6} {peak['position']:<15.2f} {peak['intensity']:<15.4f} {peak.get('fwhm', 'N/A'):<15.2f}")
    
    # 峰面积计算（针对最强峰）
    if peaks:
        strongest_peak = peaks[0]
        area_result = inference.calculate_peak_area(
            spectrum, wavelengths, strongest_peak['position']
        )
        
        print(f"\n📐 峰面积计算（{strongest_peak['position']:.1f} cm⁻¹）:")
        print(f"   峰高：{area_result.get('height', 'N/A'):.4f}")
        print(f"   面积：{area_result.get('area', 'N/A'):.2f}")
        print(f"   半高宽：{area_result.get('fwhm', 'N/A'):.2f} cm⁻¹")
    
    print("\n" + "=" * 60 + "\n")
    
    # 保存结果
    if output_path:
        result_data = {
            "input_file": str(input_file),
            "peaks": peaks,
            "peak_area": area_result if peaks else None
        }
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(result_data, f, indent=2, ensure_ascii=False)
        logger.info(f"[CLI] 分析结果已保存到：{output_path}")
    
    return True


def main():
    """主函数"""
    parser = argparse.ArgumentParser(
        description='🔬 拉曼光谱边缘客户端 - 命令行工具',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  # 采集光谱并保存
  python cli.py --acquire --output result.csv
  
  # 谱库匹配
  python cli.py --match sample.csv --top-3
  
  # 光谱分析
  python cli.py --analyze spectrum.json --output analysis.json
  
  # 设置采集参数
  python cli.py --acquire --output result.json --integration-time 500 --smoothing 5
        """
    )
    
    # 采集选项
    acquire_group = parser.add_argument_group('采集选项')
    acquire_group.add_argument('--acquire', action='store_true',
                               help='采集光谱并保存')
    acquire_group.add_argument('--integration-time', type=int, default=100,
                               help='积分时间 (ms, 默认：100)')
    acquire_group.add_argument('--accumulation', type=int, default=1,
                               help='累加次数 (默认：1)')
    acquire_group.add_argument('--smoothing', type=int, default=0,
                               help='平滑窗口大小 (默认：0)')
    acquire_group.add_argument('--noise', type=float, default=0.02,
                               help='噪声水平 (默认：0.02)')
    
    # 匹配选项
    match_group = parser.add_argument_group('匹配选项')
    match_group.add_argument('--match', type=str, metavar='FILE',
                             help='对指定光谱文件进行谱库匹配')
    match_group.add_argument('--top-k', type=int, default=5,
                             help='返回最匹配的 k 个结果 (默认：5)')
    match_group.add_argument('--threshold', type=float, default=0.6,
                             help='匹配阈值 (默认：0.6)')
    
    # 分析选项
    analyze_group = parser.add_argument_group('分析选项')
    analyze_group.add_argument('--analyze', type=str, metavar='FILE',
                               help='分析指定光谱文件')
    
    # 通用选项
    parser.add_argument('--output', '-o', type=str,
                        help='输出文件路径')
    parser.add_argument('--format', '-f', type=str, default='csv',
                        choices=['csv', 'json'],
                        help='输出格式 (默认：csv)')
    parser.add_argument('--version', '-v', action='version',
                        version='%(prog)s 1.0.0')
    
    args = parser.parse_args()
    
    # 检查是否提供了任何操作
    if not (args.acquire or args.match or args.analyze):
        parser.print_help()
        sys.exit(1)
    
    # 执行操作
    success = False
    
    if args.acquire:
        if not args.output:
            logger.error("[CLI] 请指定输出文件路径 (--output)")
            sys.exit(1)
        success = acquire_spectrum(
            args.output,
            integration_time=args.integration_time,
            accumulation_count=args.accumulation,
            smoothing_window=args.smoothing,
            noise_level=args.noise,
            format=args.format
        )
    
    elif args.match:
        success = match_library(
            args.match,
            top_k=args.top_k,
            threshold=args.threshold
        )
    
    elif args.analyze:
        success = analyze_spectrum(
            args.analyze,
            output_path=args.output
        )
    
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
